[package]
name = "intmax2-client-sdk"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow ={workspace = true} 
bincode = "1.3.3"
plonky2 = {workspace = true} 
intmax2-zkp = {workspace = true}
intmax2-interfaces = {path = "../interfaces"}
tokio = { workspace = true }
reqwest = { workspace = true}
ethers = {workspace = true}
serde_json ={workspace = true}
serde = { workspace = true}
num-bigint = "0.4.6"
config = "0.13"
aes-gcm = "0.9"
sha3 = "0.10.0"
dialoguer = "0.11.0"
console = "0.15.8"
rand = "0.8.4"
simplelog = "0.12.2"
log = "0.4.22"
chrono = "0.4.38"
regex = "1.10.6"
clap = { version = "4.5.18", features = ["derive"] }
dotenv = "0.15.0"
hex = "0.4.3"
thiserror = "1.0.64"
strum = "0.26.3"
strum_macros = "0.26.4"
rand_chacha = "0.3.1"
async-trait = "0.1.83"
base64 = "0.22.1"
env_logger = "0.11.5"
itertools = "0.13.0"
hashbrown = "0.14.5"
getrandom = { version = "0.2", features = ["js"]}
gloo-timers = { version = "0.3.0", features = ["futures"] }
ark-bn254 = "0.4.0"
ark-ff = "0.4.2"
num-traits = "0.2.19"
sha2 = "0.10.8"
serde_urlencoded = "0.7.1"
serde_qs = "0.13.0"
