on:
  push:
    branches: ["dev"]
  pull_request:
    branches: ["dev"]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  RUST_BACKTRACE: 1

jobs:
  format-check:
    name: fmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: cargo fmt
        run: cargo fmt --check --all
  doc:
    name: doc
    runs-on: ubuntu-latest
    env:
      RUSTDOCFLAGS: "-D warnings"
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
      - name: Check docs
        run: cargo doc --no-deps
  typos:
    name: typos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: typos-action
        uses: crate-ci/typos@master
  clippy:
    name: clippy
    needs: format-check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo clippy
        run: cargo clippy --tests -- -D warnings
  tests:
    name: tests
    needs: clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Rust Toolchain
        uses: dtolnay/rust-toolchain@stable
      - uses: taiki-e/install-action@cargo-nextest
      - uses: r7kamura/rust-problem-matchers@v1
      - name: Run tests
        run: cargo nextest run
